### ISSUE TITLE
Limited LED for Elm

### ISSUE THREAD

**Issue by yoid2000** [diffix/reference#250]
This is related to the discussion at https://github.com/diffix/internal-strategy/discussions/77

We want to detect when the attack conditions exist, and make an adjustment if they exist. However the attack conditions are a bit more general than given in the discussion, to allow for cases where multiple victim's exist and have the same unknown value, but also to avoid making adjustments unless there really are attack conditions.

Note that this attack must have an `unknown column` and an `isolating column`. The `unknown column` is what the attacker wants to learn, and the `isolating column` is the one that is dropped from one of the two queries comprising the difference attack. If there are more than two columns selected (almost always the case), then the remaining columns are `subset columns`, and are used to select a subset of the table within which the attack can take place.

What we want to do is, for each low-count bucket, examine each of the columns and determine if there is both an `unknown column` and an `isolating column`. (There can be multiple unknown columns. There can also be multiple isolating columns, but they are so rare as to be non-existent in practice.) If there are both kinds of columns, then some rows are adjusted.

If a bucket `victim_bkt` is low-count, then it has an `isolating column` when there is only one other bucket that matches all other column values, and that other bucket is not low-count. This is the `sibling_bkt`.

The bucket `victim_bkt` has an `unknown column` where there are no other buckets that match all other column values.

When a `victim_bkt` has both an `isolating column` and an `unknown column`, then the rows of that bucket are added to the `sibling_bkt`. 

Following is a pseudo-code algorithm for this. The query is:

```
SELECT col1,col2,...,count()
FROM table
GROUP BY 1,2,...
```

Where `count()` may be `count(DISTINCT aid)` or `count(*)`, and where the `GROUP BY` may be implicit.

The algorithm is this:
```
# There are n selected columns, C1 ... Cn
For each bucket victim_bkt:          # bucket loop
    Set sibling_bkts = []
    Set unknown_cols= []
    If victim_bkt is not low-count:
        continue    #do nothing, go to next bucket
    Set victim_cnt = count of victim_bkt   # number of rows if count(*), else 1
    Set victim_aidv_set to the AIDV Set of victim_bkt
    For each column Ci:      # loop through columns
        Find all buckets where all column values other than Ci match that of the victim_bkt
        If there is exactly one such bucket, and it is not low-count:
            Add this bucket to sibling_bkts
        Else if there are no such buckets:
            Add Ci to unknown_cols
    If sibling_bkts is not empty and unknown_cols is not empty:
        For each sibling_bkt in list of sibling_bkts:
            sibling_cnt += victim_cnt                                      # sibling_cnt is count of sibling_bkt
            Add victim_aidv_set to sibling_aidv_set                #  sibling_aidv_set is AIDV Set of sibling_bkt
            # Compute LCF, noise layers and flattening using updated sibling_cnt and sibling_aidv_set
```

-------

By way of example, suppose that there is one woman or a low-count number of women in the CS dept, and they all have the same title, and the attacker wants to learn the title. (Note that the attacker doesn't know they have same title, but if they did, and we didn't to LED, then this would be detectable.)

The query is:
```
SELECT dept, gender, title, count(*)
FROM table
GROUP by 1,2,3
```

In the bucket loop, we find a bucket with values  `dept=CS, gender=F, title=FULLPROF` is low-count. This is therefore a `victim_bkt`.

Using this `victim_bkt`, in the loop through columns, we try `Ci = dept`. We find the following buckets all non-low-count:

```
bkt1: title=FULLPROF, gender=F, Ci=math
bkt2: title=FULLPROF, gender=F, Ci=history
... and maybe more
```

Since this does not match the criteria for either `unknown_col` or `isolating_col`, we do nothing.

Continuing in the loop through columns, we try `Ci = title`. This time we don't find any other buckets, because there are no other buckets with `dept=CS, gender=F, title=SOMETHING_ELSE`. Therefore this is an `unknown_col`.

Continuing in the loop through columns, we try `Ci=gender`. We find one other bucket which is not low-count:

```
bkt1: title=FULLPROF, dept=CS, Ci=M
```

This is a `sibling_bkt`. We therefore effectively add the victims to this bucket by adding their AIDVs into `sibling_aidv_set`, and increasing `sibling_cnt` by the `victim_bkt` row count.

----------------

As a second example, suppose that there are two woman in the CS dept, but they have different titles, and the attacker wants to learn the titles.

Note that there are two difficulties for the attacker. First, it is somewhat more difficult to detect that this is the case, because one of the two might still have a relatively large positive noise component, and this might be mistaken for a bucket where both women have the same title. Second, even if the attacker can detect that the women have different titles, the attacker won't know which has which. 

So, we only need to adjust in the case where both women have the same title.

The same query is used:
```
SELECT dept, gender, title, count(*)
FROM table
GROUP by 1,2,3
```

In the bucket loop, we find a bucket with values  `dept=CS, gender=F, title=FULLPROF` with one AIDV, and another bucket with values `dept=CS, gender=F, title=ASSTPROF` and one AIDV. Both are low-count, and therefore both are `victim_bkt`.

Starting with the first `victim_bkt`, in the loop through columns, we try `Ci = dept`. We find the following non-low-count buckets:

```
bkt1: title=FULLPROF, gender=F, Ci=math
bkt2: title=FULLPROF, gender=F, Ci=history
... and maybe more
```

Since this does not match the criteria for either `unknown_col` or `isolating_col`, we do nothing.

Continuing in the loop through columns, we try `Ci = title`.  We find one matching bucket which is low-count:

```
dept=CS, gender=F, Ci=ASSTPROF
```

Since this does not match the criteria for either `unknown_col` or `isolating_col`, we do nothing.

Strictly speaking at this point we could quit for this `victim_bkt` because there is only one remaining column and it can't be both `isolating` and `unknown`, so we won't find both types of columns. 

Nevertheless, let's continue in the loop through columns, and try `Ci=gender`. We find one other bucket:

```
bkt1: title=FULLPROF, dept=CS, Ci=M
```

This matches the criteria for the `isolating column` and so is a `sibling_bkt`. However, since we don't have an `unknown column`, then no adjustment is done.

**Comment by edongashi** [comment]
> Compute LCF, noise layers and flattening using updated sibling_cnt and sibling_aidv_set

Why do we want to re-compute LCF if it's already a high-count bucket? Is it the case if the different noise layer produces some other threshold, making the bucket possibly fail LCF?

If merging a victim bucket to a parent bucket causes it to go from high-count to low count, does the algorithm become non-deterministic because now the (originally high count) parent bucket is no longer a candidate for being merged to?

Or the more generalized question would be: Can multiple victim buckets be merged to a single parent bucket (through some other combination of columns)?

**Comment by yoid2000** [comment]
> Why do we want to re-compute LCF if it's already a high-count bucket? Is it the case if the different noise layer produces some other threshold, making the bucket possibly fail LCF?

I think  you are right that we don't need to re-compute LCF. There is a small chance the sibling bucket could become LCF, but it is quite small and a corner case not worth dealing with.

**Comment by yoid2000** [comment]
> Can multiple victim buckets be merged to a single parent bucket (through some other combination of columns)?

I presume so, but it should be extremely rare in practice. But by "presume", I mean that I haven't worked it through. But it should be possible, no?

**Comment by edongashi** [comment]
> There is a small chance the sibling bucket could become LCF, but it is quite small and a corner case not worth dealing with.

I think it's OK to re-compute, but I think the re-computation should be delayed until the end of the loop, otherwise switching from HC to LC halfway may produce nondeterminism in the algorithm.

I will go with whatever is easier to implement.

**Comment by yoid2000** [comment]
> I will go with whatever is easier to implement.

yep!

**Comment by edongashi** [comment]
Just to verify, what exactly does the `if there are no such buckets` part in the else case below mean?

```
Find all buckets where all column values other than Ci match that of the victim_bkt
If there is exactly one such bucket, and it is not low-count:
    Add this bucket to sibling_bkts
Else if there are no such buckets:
    Add Ci to unknown_cols
```

Does it mean that either:

1. There are 0 matched buckets
2. There is 1 matched bucket but it is low count

Or is it only the first condition?

**Comment by yoid2000** [comment]
> Does it mean that a column is unknown if there is no **high-count** bucket that is found?

No, it means that a column is labeled as `unknown` if there are no such buckets (of the `Find all buckets...`), regardless of whether low-count or high-count.

In the second example, we have the following bit:

> Continuing in the loop through columns, we try `Ci = title`.  We find one matching bucket which is low-count:

```
dept=CS, gender=F, Ci=ASSTPROF
```

> Since this does not match the criteria for either `unknown_col` or `isolating_col`, we do nothing.

Here we do find exactly one bucket, but it doesn't match the first condition `If there is exactly one such bucket, and it is not low-count:` because the bucket is low-count. It doesn't match the second condition `Else if there are no such buckets:` because we found one bucket, not zero buckets. 

So maybe it would have been more clear to write it as:

```
Find all buckets where all column values other than Ci match that of the victim_bkt
If there are no such buckets:
    Add Ci to unknown_cols
If there is exactly one such bucket, and it is not low-count:
    Add this bucket to sibling_bkts
```

```

**Comment by edongashi** [comment]
Thanks!

**Comment by edongashi** [comment]
The following pseudocode has equivalent functionality while avoiding to iterate buckets for each column, instead they are iterated once per victim bucket.

```
for each low_count_bucket:
  siblings_per_column = for each column an empty list

  for each other_bucket:
    find index where a single column is different between low_count_bucket and other_bucket
    if such index:
      add bucket to siblings_per_column[index]

  if a column without siblings exists in siblings_per_column:
    for each list of siblings_per_column:
      if siblings.length = 1 and not siblings[0].lowCount:
        merge low_count_bucket into siblings[0]
```

**Comment by yoid2000** [comment]
@edongashi I have a question.

In my above examples, I always included the `title` column (as the unknown column).

What happens if there is no unknown column. So for instance, the query is 

```
SELECT dept, gender, count(*)
FROM table
GROUP by 1,2,3
```

And `dept=CS,gender=M` is not suppressed, but `dept=CS,gender=F` is suppressed.

Does the suppressed bucket get merged into the non-suppressed bucket?

**Comment by edongashi** [comment]
@yoid2000 I tested this and it does not merge.

1. For column `dept` it matches `math,f`, `history,f` - making this neither `isolating` nor `unknown`.
2. For column `gender` it matches `cs,m` - making this `isolating`.

Since it does not have both `isolating` and `unknown` it does not merge. Is this the expected behavior?

Dataset used for the test: https://github.com/diffix/desktop/blob/72f321cbc08a56f3c94a03697a82fda3e235d098/anonymizer/OpenDiffix.Service.Tests/Led.Tests.fs#L60-L81

**Comment by yoid2000** [comment]
> Since it does not have both `isolating` and `unknown` it does not merge. Is this the expected behavior?

That was my expected behavior. I started to have some doubts about it, but in fact I think this is the right way to go.

So ..... never mind.
