### ISSUE TITLE
Support trusted/untrusted analyst modes.

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/reference#316]
Untrusted mode should apply additional restrictions to query handling (as per the Elm spec).

**Comment by pdobacz** [comment]
Some questions:

1. The `Mode` parameter with values `Trusted` / `Untrusted` should be a new field of the `AnonymizationParams` struct?
2. Should mode influence only anonymizing queries (in the narrow sense - ones that touch tables containing AID columns) or also queries which include anonymizing aggregates (`diffix_count` etc.), "`desktop` style".
3. Extrapolating the above question: mode should be ignored for queries that neither touch AID columns nor include anonymizing aggregates?
3. Am I correct to assume, that currently `reference` implements the `Trusted` approach, or are there any pieces catering for `Untrusted` hidden somewhere?

**Comment by cristianberneanu** [comment]
1. Yes.
2. Let's go with the former.
3. Yes.
4. There is no code handling `untrusted` mode anywhere.

**Comment by pdobacz** [comment]
Re 1.: are we sure we don't prefer `TrustedMode: true/false`? Asking because `Mode: Trusted/Untrusted` is a tiny headache for the JSON decoder/encoder. Not that this should drive our API design, but no point in taking the headache-path, if we actually prefer `true/false`. WDYT?

**Comment by cristianberneanu** [comment]
I would prefer a tri-mode setting of `mode: trusted/untrusted/raw`.

**Comment by pdobacz** [comment]
is `raw` the `direct` from `pg_diffix`, where no anonymization happens?

**Comment by cristianberneanu** [comment]
Yes, `direct` sounds better and it is consistent with `pg_diffix`.

**Comment by pdobacz** [comment]
OK, but then in `reference` we've got this implicit "switch", where a query is handled differently if it touches "aid-column-bearing" tables or not. We request `direct` handling by not specifying any `--aid-columns`.

So I'm guessing now, we'd like to have `mode: direct` provide this "switch" explicitly, and we do `direct` even if one specifies `aid-columns` in tables involved?

**Comment by cristianberneanu** [comment]
`direct` mode should override the detection of personal data. But in `trusted/untrusted` mode we still need the detection, since you still wand raw access to non-personal tables. We can potentially also make `untrusted` mode the default to keep current behavior.

**Comment by pdobacz** [comment]
OK, makes sense. I'm guessing you've meant `trusted` mode the default, since this is the behavior we're having now. That's what I'm aiming at.
